### ISSUE TITLE
เขียนโค้ดการเดิน

### ISSUE THREAD

**Issue by tensept** [4ank0rn/project-game#10]
เขียนโค้ดการเดินของตัวผู้เล่นและตัวละครผู้ติดเชื้อ
-เก็บไอเทม
-ผู้ติดเชื้อ
-การรีสตาร์ท เมื่อเก็บของปลอม/ผู้ติดเชื้อ
-การเล่นใหม่
-การกดหยุด
-การกดเริ่ม

**Comment by KnackPR** [comment]
https://scratch.mit.edu/projects/729035279

**Comment by tensept** [comment]
เช็คแล้ว โอเคเลย
