### ISSUE TITLE
โค้ดเดินตามเขาวงกต

### ISSUE THREAD

**Issue by KnackPR** [4ank0rn/project-game#11]

**Comment by KnackPR** [comment]
https://scratch.mit.edu/projects/730916558 เอาไปเช็คดู

**Comment by KnackPR** [comment]
https://youtu.be/22Dpi5e9uz8

**Comment by KnackPR** [comment]
เผื่อใครอยากศึกษา

**Comment by tensept** [comment]
เช็คแล้ว โอเค ไม่มีปัญหาค่ะ
