### ISSUE TITLE
โค้ดผู้ติดเชื้อ

### ISSUE THREAD

**Issue by KnackPR** [4ank0rn/project-game#14]

**Comment by tensept** [comment]
![IMG_1341](https://user-images.githubusercontent.com/110962972/191405522-0d9dbfe7-eb4a-4bdd-b41d-5e1dbe5254a1.jpeg)

**Comment by tensept** [comment]
![IMG_1342](https://user-images.githubusercontent.com/110962972/191405547-cda6522f-4a9a-4869-89da-e9e1f8f7153b.jpeg)
