### ISSUE TITLE
แก้ bug การเก็บไอเทม

### ISSUE THREAD

**Issue by tensept** [4ank0rn/project-game#15]
มี bug ตอนที่ตัวผู้เล่นเกิดใกล้กับ R serum แต่เข้าไปเก็บแล้วไม่ผ่านด่าน

**Comment by KnackPR** [comment]
อันนี้อาจจะต้องลองมานั่งคุยกันใหม่ เหมือนจะมีปัญหาอยู่เหมือนกัน จะลองพยายามแก้ดูนะ
