### ISSUE TITLE
ออกแบบไอเทม

### ISSUE THREAD

**Issue by tensept** [4ank0rn/project-game#16]
- ออกแบบ serum จริง และ serum ปลอม

**Comment by wasiree** [comment]
![serum](https://user-images.githubusercontent.com/110921730/189899805-a8a8afac-e8c6-4cf9-b7ba-cd61113c6787.jpg)
![serum](https://user-images.githubusercontent.com/110921730/189899830-b9565605-e186-4937-8912-0d3887551a7c.png)

**Comment by wasiree** [comment]
![s1](https://user-images.githubusercontent.com/110921730/189899951-3150f76b-a8dc-4190-ac43-2f91e61c10bf.png)
![s2](https://user-images.githubusercontent.com/110921730/189899967-0cdfc4b6-f13f-46cd-af59-5a84c9c4c3e9.png)

**Comment by tensept** [comment]
โอเคค้าบ
