### ISSUE TITLE
เปลี่ยนรูปตัวละครเป็น pixel

### ISSUE THREAD

**Issue by tensept** [4ank0rn/project-game#19]

**Comment by tensept** [comment]
![IMG_1288](https://user-images.githubusercontent.com/110962972/190065258-a81c2d4a-2a58-4309-837b-e821b8e51516.jpeg)

**Comment by tensept** [comment]
![IMG_1287](https://user-images.githubusercontent.com/110962972/190065440-0d74474c-ef89-43e0-895f-cf19150f4c1f.jpeg)

**Comment by wasiree** [comment]
![l1](https://user-images.githubusercontent.com/110921730/190066619-587185ab-2574-46ee-8db0-006a509c6dda.jpg)
![l2](https://user-images.githubusercontent.com/110921730/190066632-8286f2c0-d61f-4447-9ca2-7a2a559fe1e0.jpg)
![l3](https://user-images.githubusercontent.com/110921730/190066648-c1c36473-19cc-423b-b5cd-44851f1c8bce.jpg)

**Comment by KnackPR** [comment]
จริงๆตัวละครอ่ะ เราสามารถโหลดมาเป็น file ละใส่ไว้ใน code ก็ได้นะ เพราะอันนี้คือโหลดมาใช้แล้ว ภาพมันยังแตกอยู่
