### ISSUE TITLE
ออกแบบตัวละครเพิ่มเติม

### ISSUE THREAD

**Issue by tensept** [4ank0rn/project-game#24]
ออกแบบตัวละครให้สามารถเคลื่อนไหวได้

**Comment by wasiree** [comment]
![pixilart-drawing](https://user-images.githubusercontent.com/110921730/190891928-fa53b478-876b-4aaa-9e29-7eee44649923.png)
แบบนี้ใช้ได้มั้ย หรือต้องโหลดเป็นไฟล์แบบไหน

**Comment by wasiree** [comment]
![2022-09-20](https://user-images.githubusercontent.com/110921730/191084000-85aa77ef-e019-4d25-8893-0b893f1905ce.png)
![2022-09-20 (1)](https://user-images.githubusercontent.com/110921730/191084027-50d0621f-c77d-42f0-886b-d4afc0d3bfe6.png)
ตัวละครติดเชื้อ

**Comment by wasiree** [comment]
![2022-09-20 (2)](https://user-images.githubusercontent.com/110921730/191084200-68be78f5-ad15-4aac-881c-295c121720e3.png)
![2022-09-20 (3)](https://user-images.githubusercontent.com/110921730/191084219-4d426efe-2e4a-48c8-8074-288b5e07bc81.png)

**Comment by wasiree** [comment]
![2022-09-20 (4)](https://user-images.githubusercontent.com/110921730/191171185-2a2dd7d7-d5b1-40d9-b4d9-b071846c8a39.png)
![2022-09-20 (5)](https://user-images.githubusercontent.com/110921730/191171190-6b5e3185-4e8b-48b6-96cc-f30fa5ccf31f.png)
