### ISSUE TITLE
Final Product

### ISSUE THREAD

**Issue by KnackPR** [4ank0rn/project-game#25]
เกมที่ทำเสร็จแล้ว

**Comment by tensept** [comment]
https://scratch.mit.edu/projects/734015532

**Comment by tensept** [comment]
ยังไม่เรียบร้อยนะ
- แก้แมพไม่ขึ้น
- ตัวมอนบางตัวยังเดินไม่ได้
- แก้ทิศทางไวรัสที่ปล่อยออกมา
- บอร์ดคะแนนโชว์คะแนนกับตัวหนังสือได้แต่ยังมีบางตัวอักษรที่ปรากฎขึ้นมา
- อยากให้ตัวหนังสืออยู่ในตารางที่ทำ
- ปรับพวกคีย์ทีใช้กดเล่น โค้ดบางอันยังไม่ได้แก้
